version: '3'

services:
  db:
    container_name: mysqlCursoLaravel
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306" 
    volumes:
      - /var/lib/mysql   
    image: mysql:8.0